
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.scpalarm.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.sounds.SoundEvent;
import net.minecraft.resources.ResourceLocation;

import net.mcreator.scpalarm.MoreScpAlarmMod;

public class MoreScpAlarmModSounds {
	public static final DeferredRegister<SoundEvent> REGISTRY = DeferredRegister.create(ForgeRegistries.SOUND_EVENTS, MoreScpAlarmMod.MODID);
	public static final RegistryObject<SoundEvent> BANG = REGISTRY.register("bang", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "bang")));
	public static final RegistryObject<SoundEvent> HEAVYLIGHT = REGISTRY.register("heavylight", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "heavylight")));
	public static final RegistryObject<SoundEvent> SCP173_VENT = REGISTRY.register("scp173-vent", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp173-vent")));
	public static final RegistryObject<SoundEvent> SCP173_CHAMBER = REGISTRY.register("scp173-chamber", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp173-chamber")));
	public static final RegistryObject<SoundEvent> INTRO_HORROR = REGISTRY.register("intro-horror", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-horror")));
	public static final RegistryObject<SoundEvent> INTRO_APPROACH173 = REGISTRY.register("intro-approach173", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-approach173")));
	public static final RegistryObject<SoundEvent> INTRO_ENTERCHAMBER173 = REGISTRY.register("intro-enterchamber173", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-enterchamber173")));
	public static final RegistryObject<SoundEvent> INTRO_DOORPROBLEM = REGISTRY.register("intro-doorproblem", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-doorproblem")));
	public static final RegistryObject<SoundEvent> INTRO_REFUSE1 = REGISTRY.register("intro-refuse1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-refuse1")));
	public static final RegistryObject<SoundEvent> INTRO_REFUSE2 = REGISTRY.register("intro-refuse2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-refuse2")));
	public static final RegistryObject<SoundEvent> INTRO_REFUSE3 = REGISTRY.register("intro-refuse3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-refuse3")));
	public static final RegistryObject<SoundEvent> INTRO_CONVERSATION = REGISTRY.register("intro-conversation", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-conversation")));
	public static final RegistryObject<SoundEvent> INTRO_ESCAPE = REGISTRY.register("intro-escape", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-escape")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_CONVERSATION1 = REGISTRY.register("intro-guard-conversation1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-conversation1")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_CONVERSATION3 = REGISTRY.register("intro-guard-conversation3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-conversation3")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_CONVERSATION4 = REGISTRY.register("intro-guard-conversation4", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-conversation4")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_CONVERSATION5 = REGISTRY.register("intro-guard-conversation5", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-conversation5")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_CONVERSATION2 = REGISTRY.register("intro-guard-conversation2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-conversation2")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_BALCONY_ALERT = REGISTRY.register("intro-guard-balcony-alert", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-balcony-alert")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_BALCONY_OHSH = REGISTRY.register("intro-guard-balcony-ohsh", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-balcony-ohsh")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_BALCONY_WTF = REGISTRY.register("intro-guard-balcony-wtf", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-balcony-wtf")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_ULGRIN_BEFOREDOOROPEN = REGISTRY.register("intro-guard-ulgrin-beforedooropen",
			() -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-beforedooropen")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_ULGRIN_CALLGAS = REGISTRY.register("intro-guard-ulgrin-callgas", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-callgas")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_ULGRIN_ESCORT = REGISTRY.register("intro-guard-ulgrin-escort", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escort")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_ULGRIN_ESCORTDONE = REGISTRY.register("intro-guard-ulgrin-escortdone", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortdone")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_ULGRIN_ESCORTKILL = REGISTRY.register("intro-guard-ulgrin-escortkill", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortkill")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_ULGRIN_ESCORTPISSEDOFF = REGISTRY.register("intro-guard-ulgrin-escortpissedoff",
			() -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortpissedoff")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_ULGRIN_ESCORTREFUSE = REGISTRY.register("intro-guard-ulgrin-escortrefuse",
			() -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortrefuse")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_ULGRIN_ESCORTRUN = REGISTRY.register("intro-guard-ulgrin-escortrun", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortrun")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_ULGRIN_ESCORTTERMINATED = REGISTRY.register("intro-guard-ulgrin-escortterminated",
			() -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortterminated")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_ULGRIN_EXITCELL = REGISTRY.register("intro-guard-ulgrin-exitcell", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-exitcell")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_ULGRIN_EXITCELLREFUSE = REGISTRY.register("intro-guard-ulgrin-exitcellrefuse",
			() -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-exitcellrefuse")));
	public static final RegistryObject<SoundEvent> TESLA_START = REGISTRY.register("tesla-start", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "tesla-start")));
	public static final RegistryObject<SoundEvent> TESLA_LOOP = REGISTRY.register("tesla-loop", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "tesla-loop")));
	public static final RegistryObject<SoundEvent> TESLA_END = REGISTRY.register("tesla-end", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "tesla-end")));
	public static final RegistryObject<SoundEvent> TESLA_SHOCK = REGISTRY.register("tesla-shock", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "tesla-shock")));
	public static final RegistryObject<SoundEvent> TESLA_WINDUP = REGISTRY.register("tesla-windup", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "tesla-windup")));
	public static final RegistryObject<SoundEvent> TESLA_POWERUP = REGISTRY.register("tesla-powerup", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "tesla-powerup")));
	public static final RegistryObject<SoundEvent> MTF_ANNOUNC = REGISTRY.register("mtf-announc", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-announc")));
	public static final RegistryObject<SoundEvent> MTF_173RECONTAIN = REGISTRY.register("mtf-173recontain", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-173recontain")));
	public static final RegistryObject<SoundEvent> MTF_AFTER2 = REGISTRY.register("mtf-after2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-after2")));
	public static final RegistryObject<SoundEvent> MTF_AFTER1 = REGISTRY.register("mtf-after1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-after1")));
	public static final RegistryObject<SoundEvent> MTF_CAMERA_CHECK = REGISTRY.register("mtf-camera-check", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-camera-check")));
	public static final RegistryObject<SoundEvent> MTF_CAMERA_CHAOSFOUND = REGISTRY.register("mtf-camera-chaosfound", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-camera-chaosfound")));
	public static final RegistryObject<SoundEvent> MTF_CAMERA_DCLASS = REGISTRY.register("mtf-camera-dclass", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-camera-dclass")));
	public static final RegistryObject<SoundEvent> MTF_CAMERA_NOFOUND = REGISTRY.register("mtf-camera-nofound", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-camera-nofound")));
	public static final RegistryObject<SoundEvent> MTF_BEEP = REGISTRY.register("mtf-beep", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-beep")));
	public static final RegistryObject<SoundEvent> MTF_BREATH = REGISTRY.register("mtf-breath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-breath")));
	public static final RegistryObject<SoundEvent> MTF_CLASSD = REGISTRY.register("mtf-classd", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-classd")));
	public static final RegistryObject<SoundEvent> MTF_GATEB = REGISTRY.register("mtf-gateb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-gateb")));
	public static final RegistryObject<SoundEvent> MTF_RANDOM = REGISTRY.register("mtf-random", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-random")));
	public static final RegistryObject<SoundEvent> MTF_STOP = REGISTRY.register("mtf-stop", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-stop")));
	public static final RegistryObject<SoundEvent> MTF_TARGETLOST = REGISTRY.register("mtf-targetlost", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-targetlost")));
	public static final RegistryObject<SoundEvent> MTF_TARGETTERMINATED = REGISTRY.register("mtf-targetterminated", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-targetterminated")));
	public static final RegistryObject<SoundEvent> MTF_THEREHEIS = REGISTRY.register("mtf-thereheis", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-thereheis")));
	public static final RegistryObject<SoundEvent> MTF_THREATANNOUNC = REGISTRY.register("mtf-threatannounc", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-threatannounc")));
	public static final RegistryObject<SoundEvent> MTF_THREATANNOUNCFINAL = REGISTRY.register("mtf-threatannouncfinal", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-threatannouncfinal")));
	public static final RegistryObject<SoundEvent> MTF_THREATANNOUNCPOSSESSION = REGISTRY.register("mtf-threatannouncpossession", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-threatannouncpossession")));
	public static final RegistryObject<SoundEvent> LURESUBJECT_IDLE = REGISTRY.register("luresubject-idle", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "luresubject-idle")));
	public static final RegistryObject<SoundEvent> LURESUBJECT_106BAIT = REGISTRY.register("luresubject-106bait", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "luresubject-106bait")));
	public static final RegistryObject<SoundEvent> LURESUBJECT_SNIFFLING = REGISTRY.register("luresubject-sniffling", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "luresubject-sniffling")));
	public static final RegistryObject<SoundEvent> GENERATOR_COUNT = REGISTRY.register("generator-count", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "generator-count")));
	public static final RegistryObject<SoundEvent> DOOR_CHECKPIONT = REGISTRY.register("door-checkpiont", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "door-checkpiont")));
	public static final RegistryObject<SoundEvent> DOOR_BIGDOOR_OPEN = REGISTRY.register("door-bigdoor-open", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "door-bigdoor-open")));
	public static final RegistryObject<SoundEvent> DOOR_BIGDOOR_CLOSE = REGISTRY.register("door-bigdoor-close", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "door-bigdoor-close")));
	public static final RegistryObject<SoundEvent> DOOR_CLOSE079 = REGISTRY.register("door-close079", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "door-close079")));
	public static final RegistryObject<SoundEvent> DOOR_ERROR = REGISTRY.register("door-error", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "door-error")));
	public static final RegistryObject<SoundEvent> DOOR_OPEN079 = REGISTRY.register("door-open079", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "door-open079")));
	public static final RegistryObject<SoundEvent> DOOR_OPEN173 = REGISTRY.register("door-open173", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "door-open173")));
	public static final RegistryObject<SoundEvent> DOOR_OPENFAST = REGISTRY.register("door-openfast", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "door-openfast")));
	public static final RegistryObject<SoundEvent> AMBIENTA = REGISTRY.register("ambienta", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "ambienta")));
	public static final RegistryObject<SoundEvent> ROOM_RUMBLE = REGISTRY.register("room-rumble", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "room-rumble")));
	public static final RegistryObject<SoundEvent> ROOM_PULSING = REGISTRY.register("room-pulsing", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "room-pulsing")));
	public static final RegistryObject<SoundEvent> ROOM_SERVER = REGISTRY.register("room-server", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "room-server")));
	public static final RegistryObject<SoundEvent> ROOM_VENTILATION = REGISTRY.register("room-ventilation", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "room-ventilation")));
	public static final RegistryObject<SoundEvent> DOOR_BREAK = REGISTRY.register("door-break", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "door-break")));
	public static final RegistryObject<SoundEvent> LEVERFLIP = REGISTRY.register("leverflip", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "leverflip")));
	public static final RegistryObject<SoundEvent> REFUSE = REGISTRY.register("refuse", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "refuse")));
	public static final RegistryObject<SoundEvent> SMOKE = REGISTRY.register("smoke", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "smoke")));
	public static final RegistryObject<SoundEvent> HORROR = REGISTRY.register("horror", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "horror")));
	public static final RegistryObject<SoundEvent> LOCKROOM = REGISTRY.register("lockroom", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "lockroom")));
	public static final RegistryObject<SoundEvent> GENERATOR_ON = REGISTRY.register("generator-on", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "generator-on")));
	public static final RegistryObject<SoundEvent> GENERATOR_OFF = REGISTRY.register("generator-off", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "generator-off")));
	public static final RegistryObject<SoundEvent> GENERATOR_1OF5 = REGISTRY.register("generator-1of5", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "generator-1of5")));
	public static final RegistryObject<SoundEvent> GENERATOR_2OF5 = REGISTRY.register("generator-2of5", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "generator-2of5")));
	public static final RegistryObject<SoundEvent> GENERATOR_3OF5 = REGISTRY.register("generator-3of5", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "generator-3of5")));
	public static final RegistryObject<SoundEvent> GENERATOR_4OF5 = REGISTRY.register("generator-4of5", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "generator-4of5")));
	public static final RegistryObject<SoundEvent> GENERATOR_5OF5 = REGISTRY.register("generator-5of5", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "generator-5of5")));
	public static final RegistryObject<SoundEvent> GENERATOR_OVERCHARGE = REGISTRY.register("generator-overcharge", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "generator-overcharge")));
	public static final RegistryObject<SoundEvent> GENERATOR_DONE = REGISTRY.register("generator-done", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "generator-done")));
	public static final RegistryObject<SoundEvent> ALARM_BREACH = REGISTRY.register("alarm-breach", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "alarm-breach")));
	public static final RegistryObject<SoundEvent> MTF_TESLA_OFF = REGISTRY.register("mtf-tesla-off", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-tesla-off")));
	public static final RegistryObject<SoundEvent> MTF_TESLA_REQUESTING = REGISTRY.register("mtf-tesla-requesting", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "mtf-tesla-requesting")));
	public static final RegistryObject<SoundEvent> SCP_079_BROADCAST = REGISTRY.register("scp-079-broadcast", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-079-broadcast")));
	public static final RegistryObject<SoundEvent> SCP_079_GATEB = REGISTRY.register("scp-079-gateb", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-079-gateb")));
	public static final RegistryObject<SoundEvent> SCP_079_REFUSE = REGISTRY.register("scp-079-refuse", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-079-refuse")));
	public static final RegistryObject<SoundEvent> SCP_914_OPEN = REGISTRY.register("scp-914-open", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-914-open")));
	public static final RegistryObject<SoundEvent> SCP_914_CLOSE = REGISTRY.register("scp-914-close", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-914-close")));
	public static final RegistryObject<SoundEvent> SCP_079_TESTROOM = REGISTRY.register("scp-079-testroom", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-079-testroom")));
	public static final RegistryObject<SoundEvent> SCP_079_SPEECH = REGISTRY.register("scp-079-speech", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-079-speech")));
	public static final RegistryObject<SoundEvent> SCP_939_0ATTACK = REGISTRY.register("scp-939-0attack", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-939-0attack")));
	public static final RegistryObject<SoundEvent> SCP_939_0LURE = REGISTRY.register("scp-939-0lure", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-939-0lure")));
	public static final RegistryObject<SoundEvent> SCP_939_1ALERT = REGISTRY.register("scp-939-1alert", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-939-1alert")));
	public static final RegistryObject<SoundEvent> SCP_939_1LURE = REGISTRY.register("scp-939-1lure", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-939-1lure")));
	public static final RegistryObject<SoundEvent> SCP_939_2ATTACK = REGISTRY.register("scp-939-2attack", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-939-2attack")));
	public static final RegistryObject<SoundEvent> SCP_914_REFINING = REGISTRY.register("scp-914-refining", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-914-refining")));
	public static final RegistryObject<SoundEvent> SCP_939_2LURE = REGISTRY.register("scp-939-2lure", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-939-2lure")));
	public static final RegistryObject<SoundEvent> SCP_939_1ATTACK = REGISTRY.register("scp-939-1attack", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-939-1attack")));
	public static final RegistryObject<SoundEvent> SCP_939_ALERT = REGISTRY.register("scp-939-alert", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-939-alert")));
	public static final RegistryObject<SoundEvent> SCP_939_0ALERT = REGISTRY.register("scp-939-0alert", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-939-0alert")));
	public static final RegistryObject<SoundEvent> SCP_106_CORROSION = REGISTRY.register("scp-106-corrosion", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-106-corrosion")));
	public static final RegistryObject<SoundEvent> SCP_106_DECAY = REGISTRY.register("scp-106-decay", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-106-decay")));
	public static final RegistryObject<SoundEvent> SCP_106_WALLDECAY = REGISTRY.register("scp-106-walldecay", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-106-walldecay")));
	public static final RegistryObject<SoundEvent> SCP_106_BREATHING = REGISTRY.register("scp-106-breathing", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-106-breathing")));
	public static final RegistryObject<SoundEvent> SCP_106_LAUGH = REGISTRY.register("scp-106-laugh", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-106-laugh")));
	public static final RegistryObject<SoundEvent> SCP_049_BREATH = REGISTRY.register("scp-049-breath", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-049-breath")));
	public static final RegistryObject<SoundEvent> SCP_049_KIDNAP = REGISTRY.register("scp-049-kidnap", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-049-kidnap")));
	public static final RegistryObject<SoundEvent> SCP_049_SPOTTED = REGISTRY.register("scp-049-spotted", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-049-spotted")));
	public static final RegistryObject<SoundEvent> SCP_049_ROOM = REGISTRY.register("scp-049-room", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-049-room")));
	public static final RegistryObject<SoundEvent> SCP_049_TAKEOFHAZMAT = REGISTRY.register("scp-049-takeofhazmat", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-049-takeofhazmat")));
	public static final RegistryObject<SoundEvent> SCP_049_714 = REGISTRY.register("scp-049-714", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-049-714")));
	public static final RegistryObject<SoundEvent> ALARM_1 = REGISTRY.register("alarm-1", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "alarm-1")));
	public static final RegistryObject<SoundEvent> ALARM_2 = REGISTRY.register("alarm-2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "alarm-2")));
	public static final RegistryObject<SoundEvent> ALARM_3 = REGISTRY.register("alarm-3", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "alarm-3")));
	public static final RegistryObject<SoundEvent> ALARM_4 = REGISTRY.register("alarm-4", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "alarm-4")));
	public static final RegistryObject<SoundEvent> HEAVY_AMBIENT = REGISTRY.register("heavy-ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "heavy-ambient")));
	public static final RegistryObject<SoundEvent> LIGHT_AMBIENT = REGISTRY.register("light-ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "light-ambient")));
	public static final RegistryObject<SoundEvent> INTRO_GUARD_MUSIC = REGISTRY.register("intro-guard-music", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "intro-guard-music")));
	public static final RegistryObject<SoundEvent> ROOM_895 = REGISTRY.register("room-895", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "room-895")));
	public static final RegistryObject<SoundEvent> DECONTAMINATION_1M = REGISTRY.register("decontamination-1m", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "decontamination-1m")));
	public static final RegistryObject<SoundEvent> DECONTAMINATION_30S = REGISTRY.register("decontamination-30s", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "decontamination-30s")));
	public static final RegistryObject<SoundEvent> DECONTAMINATION_END = REGISTRY.register("decontamination-end", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "decontamination-end")));
	public static final RegistryObject<SoundEvent> ROOM_SERVER2 = REGISTRY.register("room-server2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "room-server2")));
	public static final RegistryObject<SoundEvent> DECONTAMINATION_START = REGISTRY.register("decontamination-start", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "decontamination-start")));
	public static final RegistryObject<SoundEvent> DECONTAMINATION_10M = REGISTRY.register("decontamination-10m", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "decontamination-10m")));
	public static final RegistryObject<SoundEvent> DECONTAMINATION_5M = REGISTRY.register("decontamination-5m", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "decontamination-5m")));
	public static final RegistryObject<SoundEvent> ENTRANCE_AMBIENT = REGISTRY.register("entrance-ambient", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "entrance-ambient")));
	public static final RegistryObject<SoundEvent> ALARM_5 = REGISTRY.register("alarm-5", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "alarm-5")));
	public static final RegistryObject<SoundEvent> ELEVATOR_OPEN = REGISTRY.register("elevator-open", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "elevator-open")));
	public static final RegistryObject<SoundEvent> ELEVATOR_LOOP = REGISTRY.register("elevator-loop", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "elevator-loop")));
	public static final RegistryObject<SoundEvent> ELEVATOR_CLOSING = REGISTRY.register("elevator-closing", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "elevator-closing")));
	public static final RegistryObject<SoundEvent> ELEVATOR_DING = REGISTRY.register("elevator-ding", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "elevator-ding")));
	public static final RegistryObject<SoundEvent> SCP_049_SEARCHING = REGISTRY.register("scp-049-searching", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-049-searching")));
	public static final RegistryObject<SoundEvent> WARHEAD_V2 = REGISTRY.register("warhead-v2", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "warhead-v2")));
	public static final RegistryObject<SoundEvent> DOOR_VAULT_CLOSE = REGISTRY.register("door-vault-close", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "door-vault-close")));
	public static final RegistryObject<SoundEvent> DOOR_VAULT_OPEN = REGISTRY.register("door-vault-open", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "door-vault-open")));
	public static final RegistryObject<SoundEvent> SCP_106_CHASE = REGISTRY.register("scp-106-chase", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-106-chase")));
	public static final RegistryObject<SoundEvent> SCP_106_MAGNET_UP = REGISTRY.register("scp-106-magnet-up", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-106-magnet-up")));
	public static final RegistryObject<SoundEvent> SCP_106_MAGNET_DOWN = REGISTRY.register("scp-106-magnet-down", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "scp-106-magnet-down")));
	public static final RegistryObject<SoundEvent> DOOR_NUKEGATESIREN = REGISTRY.register("door-nukegatesiren", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "door-nukegatesiren")));
	public static final RegistryObject<SoundEvent> WARHEAD_EXTERIOR = REGISTRY.register("warhead-exterior", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "warhead-exterior")));
	public static final RegistryObject<SoundEvent> WARHEAD_INTERIOR = REGISTRY.register("warhead-interior", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "warhead-interior")));
	public static final RegistryObject<SoundEvent> COMMOTIONA = REGISTRY.register("commotiona", () -> SoundEvent.createVariableRangeEvent(new ResourceLocation("more_scp_alarm", "commotiona")));
}
