modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"

[[mods]]
modId="more_scp_alarm"
version="2.0.0"
displayName="More SCP Alarm"
credits="SCP:CB And SCP:SL"
displayURL="https://github.com/5UP3RTH30B4G/More-SCP-Alarm"
logoFile="logo.png"
authors="5UP3R TH30 B4G"
description='''
More SCP Alarm is a mod that add SFX and block of any SCP's game !
'''

[[dependencies.more_scp_alarm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

[[dependencies.more_scp_alarm]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.26]"
    ordering="NONE"
    side="BOTH"



