modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="scp_alarm"
version="3.0.0"
displayName="More SCP Alarm"
modClass="scp_alarm.scp_alarm"
displayURL="https://github.com/5UP3RTH30B4G/More-SCP-Alarm"
logoFile="logo.png"
credits="SCP:CB And SCP:SL"
authors="5UP3R TH30 B4G"
description="More SCP Alarm is a mod that add SFX and block of any SCP's game !"
issueTrackerURL="https://github.com/5UP3RTH30B4G/More-SCP-Alarm/issues"