/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.scpalarm;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class MoreScpAlarmModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();

	public MoreScpAlarmModElements() {
		sounds.put(new ResourceLocation("more_scp_alarm", "bang"), new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "bang")));
		sounds.put(new ResourceLocation("more_scp_alarm", "heavylight"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "heavylight")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp173-vent"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp173-vent")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp173-chamber"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp173-chamber")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-horror"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-horror")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-approach173"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-approach173")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-enterchamber173"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-enterchamber173")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-doorproblem"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-doorproblem")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-refuse1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-refuse1")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-refuse2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-refuse2")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-refuse3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-refuse3")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-conversation"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-conversation")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-escape"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-escape")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-conversation1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-conversation1")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-conversation3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-conversation3")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-conversation4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-conversation4")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-conversation5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-conversation5")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-conversation2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-conversation2")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-balcony-alert"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-balcony-alert")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-balcony-ohsh"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-balcony-ohsh")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-balcony-wtf"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-balcony-wtf")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-beforedooropen"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-beforedooropen")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-callgas"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-callgas")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escort"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escort")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortdone"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortdone")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortkill"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortkill")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortpissedoff"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortpissedoff")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortrefuse"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortrefuse")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortrun"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortrun")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortterminated"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-escortterminated")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-exitcell"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-exitcell")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-exitcellrefuse"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-ulgrin-exitcellrefuse")));
		sounds.put(new ResourceLocation("more_scp_alarm", "tesla-start"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "tesla-start")));
		sounds.put(new ResourceLocation("more_scp_alarm", "tesla-loop"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "tesla-loop")));
		sounds.put(new ResourceLocation("more_scp_alarm", "tesla-end"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "tesla-end")));
		sounds.put(new ResourceLocation("more_scp_alarm", "tesla-shock"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "tesla-shock")));
		sounds.put(new ResourceLocation("more_scp_alarm", "tesla-windup"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "tesla-windup")));
		sounds.put(new ResourceLocation("more_scp_alarm", "tesla-powerup"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "tesla-powerup")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-announc"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-announc")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-173recontain"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-173recontain")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-after2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-after2")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-after1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-after1")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-camera-check"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-camera-check")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-camera-chaosfound"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-camera-chaosfound")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-camera-dclass"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-camera-dclass")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-camera-nofound"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-camera-nofound")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-beep"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-beep")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-breath"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-breath")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-classd"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-classd")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-gateb"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-gateb")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-random"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-random")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-stop"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-stop")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-targetlost"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-targetlost")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-targetterminated"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-targetterminated")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-thereheis"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-thereheis")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-threatannounc"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-threatannounc")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-threatannouncfinal"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-threatannouncfinal")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-threatannouncpossession"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-threatannouncpossession")));
		sounds.put(new ResourceLocation("more_scp_alarm", "luresubject-idle"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "luresubject-idle")));
		sounds.put(new ResourceLocation("more_scp_alarm", "luresubject-106bait"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "luresubject-106bait")));
		sounds.put(new ResourceLocation("more_scp_alarm", "luresubject-sniffling"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "luresubject-sniffling")));
		sounds.put(new ResourceLocation("more_scp_alarm", "generator-count"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "generator-count")));
		sounds.put(new ResourceLocation("more_scp_alarm", "door-checkpiont"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "door-checkpiont")));
		sounds.put(new ResourceLocation("more_scp_alarm", "door-bigdoor-open"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "door-bigdoor-open")));
		sounds.put(new ResourceLocation("more_scp_alarm", "door-bigdoor-close"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "door-bigdoor-close")));
		sounds.put(new ResourceLocation("more_scp_alarm", "door-close079"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "door-close079")));
		sounds.put(new ResourceLocation("more_scp_alarm", "door-error"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "door-error")));
		sounds.put(new ResourceLocation("more_scp_alarm", "door-open079"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "door-open079")));
		sounds.put(new ResourceLocation("more_scp_alarm", "door-open173"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "door-open173")));
		sounds.put(new ResourceLocation("more_scp_alarm", "door-openfast"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "door-openfast")));
		sounds.put(new ResourceLocation("more_scp_alarm", "ambienta"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "ambienta")));
		sounds.put(new ResourceLocation("more_scp_alarm", "room-rumble"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "room-rumble")));
		sounds.put(new ResourceLocation("more_scp_alarm", "room-pulsing"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "room-pulsing")));
		sounds.put(new ResourceLocation("more_scp_alarm", "room-server"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "room-server")));
		sounds.put(new ResourceLocation("more_scp_alarm", "room-ventilation"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "room-ventilation")));
		sounds.put(new ResourceLocation("more_scp_alarm", "door-break"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "door-break")));
		sounds.put(new ResourceLocation("more_scp_alarm", "leverflip"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "leverflip")));
		sounds.put(new ResourceLocation("more_scp_alarm", "refuse"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "refuse")));
		sounds.put(new ResourceLocation("more_scp_alarm", "smoke"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "smoke")));
		sounds.put(new ResourceLocation("more_scp_alarm", "horror"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "horror")));
		sounds.put(new ResourceLocation("more_scp_alarm", "lockroom"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "lockroom")));
		sounds.put(new ResourceLocation("more_scp_alarm", "generator-on"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "generator-on")));
		sounds.put(new ResourceLocation("more_scp_alarm", "generator-off"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "generator-off")));
		sounds.put(new ResourceLocation("more_scp_alarm", "generator-1of5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "generator-1of5")));
		sounds.put(new ResourceLocation("more_scp_alarm", "generator-2of5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "generator-2of5")));
		sounds.put(new ResourceLocation("more_scp_alarm", "generator-3of5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "generator-3of5")));
		sounds.put(new ResourceLocation("more_scp_alarm", "generator-4of5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "generator-4of5")));
		sounds.put(new ResourceLocation("more_scp_alarm", "generator-5of5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "generator-5of5")));
		sounds.put(new ResourceLocation("more_scp_alarm", "generator-overcharge"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "generator-overcharge")));
		sounds.put(new ResourceLocation("more_scp_alarm", "generator-done"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "generator-done")));
		sounds.put(new ResourceLocation("more_scp_alarm", "alarm-breach"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "alarm-breach")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-tesla-off"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-tesla-off")));
		sounds.put(new ResourceLocation("more_scp_alarm", "mtf-tesla-requesting"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "mtf-tesla-requesting")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-079-broadcast"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-079-broadcast")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-079-gateb"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-079-gateb")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-079-refuse"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-079-refuse")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-914-open"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-914-open")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-914-close"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-914-close")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-079-testroom"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-079-testroom")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-079-speech"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-079-speech")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-939-0attack"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-939-0attack")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-939-0lure"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-939-0lure")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-939-1alert"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-939-1alert")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-939-1lure"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-939-1lure")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-939-2attack"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-939-2attack")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-914-refining"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-914-refining")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-939-2lure"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-939-2lure")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-939-1attack"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-939-1attack")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-939-alert"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-939-alert")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-939-0alert"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-939-0alert")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-106-corrosion"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-106-corrosion")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-106-decay"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-106-decay")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-106-walldecay"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-106-walldecay")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-106-breathing"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-106-breathing")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-106-laugh"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-106-laugh")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-049-breath"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-049-breath")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-049-kidnap"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-049-kidnap")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-049-spotted"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-049-spotted")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-049-room"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-049-room")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-049-takeofhazmat"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-049-takeofhazmat")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-049-714"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-049-714")));
		sounds.put(new ResourceLocation("more_scp_alarm", "alarm-1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "alarm-1")));
		sounds.put(new ResourceLocation("more_scp_alarm", "alarm-2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "alarm-2")));
		sounds.put(new ResourceLocation("more_scp_alarm", "alarm-3"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "alarm-3")));
		sounds.put(new ResourceLocation("more_scp_alarm", "alarm-4"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "alarm-4")));
		sounds.put(new ResourceLocation("more_scp_alarm", "heavy-ambient"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "heavy-ambient")));
		sounds.put(new ResourceLocation("more_scp_alarm", "light-ambient"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "light-ambient")));
		sounds.put(new ResourceLocation("more_scp_alarm", "intro-guard-music"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "intro-guard-music")));
		sounds.put(new ResourceLocation("more_scp_alarm", "room-895"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "room-895")));
		sounds.put(new ResourceLocation("more_scp_alarm", "decontamination-1m"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "decontamination-1m")));
		sounds.put(new ResourceLocation("more_scp_alarm", "decontamination-30s"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "decontamination-30s")));
		sounds.put(new ResourceLocation("more_scp_alarm", "decontamination-end"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "decontamination-end")));
		sounds.put(new ResourceLocation("more_scp_alarm", "room-server2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "room-server2")));
		sounds.put(new ResourceLocation("more_scp_alarm", "decontamination-start"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "decontamination-start")));
		sounds.put(new ResourceLocation("more_scp_alarm", "decontamination-10m"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "decontamination-10m")));
		sounds.put(new ResourceLocation("more_scp_alarm", "decontamination-5m"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "decontamination-5m")));
		sounds.put(new ResourceLocation("more_scp_alarm", "entrance-ambient"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "entrance-ambient")));
		sounds.put(new ResourceLocation("more_scp_alarm", "alarm-5"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "alarm-5")));
		sounds.put(new ResourceLocation("more_scp_alarm", "elevator-open"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "elevator-open")));
		sounds.put(new ResourceLocation("more_scp_alarm", "elevator-loop"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "elevator-loop")));
		sounds.put(new ResourceLocation("more_scp_alarm", "elevator-closing"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "elevator-closing")));
		sounds.put(new ResourceLocation("more_scp_alarm", "elevator-ding"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "elevator-ding")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-049-searching"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-049-searching")));
		sounds.put(new ResourceLocation("more_scp_alarm", "warhead-v2"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "warhead-v2")));
		sounds.put(new ResourceLocation("more_scp_alarm", "door-vault-close"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "door-vault-close")));
		sounds.put(new ResourceLocation("more_scp_alarm", "door-vault-open"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "door-vault-open")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-106-chase"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-106-chase")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-106-magnet-up"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-106-magnet-up")));
		sounds.put(new ResourceLocation("more_scp_alarm", "scp-106-magnet-down"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "scp-106-magnet-down")));
		sounds.put(new ResourceLocation("more_scp_alarm", "door-nukegatesiren"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "door-nukegatesiren")));
		sounds.put(new ResourceLocation("more_scp_alarm", "warhead-exterior"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "warhead-exterior")));
		sounds.put(new ResourceLocation("more_scp_alarm", "warhead-interior"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "warhead-interior")));
		sounds.put(new ResourceLocation("more_scp_alarm", "commotiona"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("more_scp_alarm", "commotiona")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("more_scp_alarm").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == MoreScpAlarmModElements.ModElement.class)
						elements.add((MoreScpAlarmModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(MoreScpAlarmModElements.ModElement::initElements);
		MinecraftForge.EVENT_BUS.register(new MoreScpAlarmModVariables(this));
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	private int messageID = 0;

	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		MoreScpAlarmMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}

		protected final MoreScpAlarmModElements elements;
		protected final int sortid;

		public ModElement(MoreScpAlarmModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
