
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.theo.scpalarm.init;

import net.theo.scpalarm.item.LogoItem;
import net.theo.scpalarm.item.Guirand3Item;
import net.theo.scpalarm.item.Guirand2Item;
import net.theo.scpalarm.item.DocstrangeItem;
import net.theo.scpalarm.item.DocscItem;
import net.theo.scpalarm.item.DocrpItem;
import net.theo.scpalarm.item.Docrand1Item;
import net.theo.scpalarm.item.DocoriItem;
import net.theo.scpalarm.item.DocndpItem;
import net.theo.scpalarm.item.DocmtfItem;
import net.theo.scpalarm.item.DocmspItem;
import net.theo.scpalarm.item.DocmapItem;
import net.theo.scpalarm.item.Docl6Item;
import net.theo.scpalarm.item.Docl5Item;
import net.theo.scpalarm.item.Docl4Item;
import net.theo.scpalarm.item.Docl3Item;
import net.theo.scpalarm.item.Docl2Item;
import net.theo.scpalarm.item.Docl1Item;
import net.theo.scpalarm.item.Docir106Item;
import net.theo.scpalarm.item.DocgonzalesItem;
import net.theo.scpalarm.item.Docf6Item;
import net.theo.scpalarm.item.Docf5Item;
import net.theo.scpalarm.item.Docf4Item;
import net.theo.scpalarm.item.DocdanItem;
import net.theo.scpalarm.item.DocbjcItem;
import net.theo.scpalarm.item.DocarceItem;
import net.theo.scpalarm.item.DocacItem;
import net.theo.scpalarm.item.Doc970Item;
import net.theo.scpalarm.item.Doc966Item;
import net.theo.scpalarm.item.Doc93armItem;
import net.theo.scpalarm.item.Doc939Item;
import net.theo.scpalarm.item.Doc914Item;
import net.theo.scpalarm.item.Doc895Item;
import net.theo.scpalarm.item.Doc860Item;
import net.theo.scpalarm.item.Doc8601Item;
import net.theo.scpalarm.item.Doc714Item;
import net.theo.scpalarm.item.Doc682Item;
import net.theo.scpalarm.item.Doc513Item;
import net.theo.scpalarm.item.Doc500Item;
import net.theo.scpalarm.item.Doc427Item;
import net.theo.scpalarm.item.Doc372Item;
import net.theo.scpalarm.item.Doc173Item;
import net.theo.scpalarm.item.Doc1499Item;
import net.theo.scpalarm.item.Doc1162Item;
import net.theo.scpalarm.item.Doc1123Item;
import net.theo.scpalarm.item.Doc109Item;
import net.theo.scpalarm.item.Doc106Item;
import net.theo.scpalarm.item.Doc1062Item;
import net.theo.scpalarm.item.Doc1048aItem;
import net.theo.scpalarm.item.Doc1048Item;
import net.theo.scpalarm.item.Doc096Item;
import net.theo.scpalarm.item.Doc079Item;
import net.theo.scpalarm.item.Doc049Item;
import net.theo.scpalarm.item.Doc038Item;
import net.theo.scpalarm.item.Doc035adItem;
import net.theo.scpalarm.item.Doc035Item;
import net.theo.scpalarm.item.Doc012Item;
import net.theo.scpalarm.item.Doc008Item;
import net.theo.scpalarm.MoreScpAlarmMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

public class MoreScpAlarmModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MoreScpAlarmMod.MODID);
	public static final RegistryObject<Item> GAZ = block(MoreScpAlarmModBlocks.GAZ);
	public static final RegistryObject<Item> LOGO = REGISTRY.register("logo", () -> new LogoItem());
	public static final RegistryObject<Item> GATE_1 = block(MoreScpAlarmModBlocks.GATE_1);
	public static final RegistryObject<Item> GATE_2 = block(MoreScpAlarmModBlocks.GATE_2);
	public static final RegistryObject<Item> GATE_3 = block(MoreScpAlarmModBlocks.GATE_3);
	public static final RegistryObject<Item> GATE_4 = block(MoreScpAlarmModBlocks.GATE_4);
	public static final RegistryObject<Item> DOOR_5 = block(MoreScpAlarmModBlocks.DOOR_5);
	public static final RegistryObject<Item> DOOR_6 = block(MoreScpAlarmModBlocks.DOOR_6);
	public static final RegistryObject<Item> DOOR_7 = block(MoreScpAlarmModBlocks.DOOR_7);
	public static final RegistryObject<Item> DOOR_8 = block(MoreScpAlarmModBlocks.DOOR_8);
	public static final RegistryObject<Item> DOOR_FRAME = block(MoreScpAlarmModBlocks.DOOR_FRAME);
	public static final RegistryObject<Item> ALARMLABEL = block(MoreScpAlarmModBlocks.ALARMLABEL);
	public static final RegistryObject<Item> ALARMSENDER = block(MoreScpAlarmModBlocks.ALARMSENDER);
	public static final RegistryObject<Item> ALARMVA = block(MoreScpAlarmModBlocks.ALARMVA);
	public static final RegistryObject<Item> TVCHECKPOINT = block(MoreScpAlarmModBlocks.TVCHECKPOINT);
	public static final RegistryObject<Item> TVOFF = block(MoreScpAlarmModBlocks.TVOFF);
	public static final RegistryObject<Item> TVLIGHT = block(MoreScpAlarmModBlocks.TVLIGHT);
	public static final RegistryObject<Item> LIGHTOFF = block(MoreScpAlarmModBlocks.LIGHTOFF);
	public static final RegistryObject<Item> TRIG_079 = block(MoreScpAlarmModBlocks.TRIG_079);
	public static final RegistryObject<Item> TV_079 = block(MoreScpAlarmModBlocks.TV_079);
	public static final RegistryObject<Item> ALARMVA_2 = block(MoreScpAlarmModBlocks.ALARMVA_2);
	public static final RegistryObject<Item> ALARMVA_3 = block(MoreScpAlarmModBlocks.ALARMVA_3);
	public static final RegistryObject<Item> TV_895 = block(MoreScpAlarmModBlocks.TV_895);
	public static final RegistryObject<Item> TV_895OFF = block(MoreScpAlarmModBlocks.TV_895OFF);
	public static final RegistryObject<Item> NEWDOOR = block(MoreScpAlarmModBlocks.NEWDOOR);
	public static final RegistryObject<Item> LABEL_008 = block(MoreScpAlarmModBlocks.LABEL_008);
	public static final RegistryObject<Item> LABEL_012 = block(MoreScpAlarmModBlocks.LABEL_012);
	public static final RegistryObject<Item> LABEL_002 = block(MoreScpAlarmModBlocks.LABEL_002);
	public static final RegistryObject<Item> LABEL_005 = block(MoreScpAlarmModBlocks.LABEL_005);
	public static final RegistryObject<Item> LABEL_006 = block(MoreScpAlarmModBlocks.LABEL_006);
	public static final RegistryObject<Item> LABEL_009 = block(MoreScpAlarmModBlocks.LABEL_009);
	public static final RegistryObject<Item> LABEL_015 = block(MoreScpAlarmModBlocks.LABEL_015);
	public static final RegistryObject<Item> LABEL_019 = block(MoreScpAlarmModBlocks.LABEL_019);
	public static final RegistryObject<Item> LABEL_020 = block(MoreScpAlarmModBlocks.LABEL_020);
	public static final RegistryObject<Item> LABEL_023 = block(MoreScpAlarmModBlocks.LABEL_023);
	public static final RegistryObject<Item> POSTER_294 = block(MoreScpAlarmModBlocks.POSTER_294);
	public static final RegistryObject<Item> LABEL_027 = block(MoreScpAlarmModBlocks.LABEL_027);
	public static final RegistryObject<Item> LABEL_049 = block(MoreScpAlarmModBlocks.LABEL_049);
	public static final RegistryObject<Item> LABEL_053 = block(MoreScpAlarmModBlocks.LABEL_053);
	public static final RegistryObject<Item> LABEL_059FR = block(MoreScpAlarmModBlocks.LABEL_059FR);
	public static final RegistryObject<Item> LABEL_063 = block(MoreScpAlarmModBlocks.LABEL_063);
	public static final RegistryObject<Item> LABEL_079 = block(MoreScpAlarmModBlocks.LABEL_079);
	public static final RegistryObject<Item> LABEL_087 = block(MoreScpAlarmModBlocks.LABEL_087);
	public static final RegistryObject<Item> LABEL_096 = block(MoreScpAlarmModBlocks.LABEL_096);
	public static final RegistryObject<Item> LABEL_098 = block(MoreScpAlarmModBlocks.LABEL_098);
	public static final RegistryObject<Item> LABEL_1000 = block(MoreScpAlarmModBlocks.LABEL_1000);
	public static final RegistryObject<Item> LABEL_1025 = block(MoreScpAlarmModBlocks.LABEL_1025);
	public static final RegistryObject<Item> LABEL_1032_RU = block(MoreScpAlarmModBlocks.LABEL_1032_RU);
	public static final RegistryObject<Item> LABEL_1048 = block(MoreScpAlarmModBlocks.LABEL_1048);
	public static final RegistryObject<Item> LABEL_1057 = block(MoreScpAlarmModBlocks.LABEL_1057);
	public static final RegistryObject<Item> LABEL_106 = block(MoreScpAlarmModBlocks.LABEL_106);
	public static final RegistryObject<Item> LABEL_1074 = block(MoreScpAlarmModBlocks.LABEL_1074);
	public static final RegistryObject<Item> LABEL_109 = block(MoreScpAlarmModBlocks.LABEL_109);
	public static final RegistryObject<Item> LABEL_111 = block(MoreScpAlarmModBlocks.LABEL_111);
	public static final RegistryObject<Item> LABEL_1162 = block(MoreScpAlarmModBlocks.LABEL_1162);
	public static final RegistryObject<Item> LABEL_124 = block(MoreScpAlarmModBlocks.LABEL_124);
	public static final RegistryObject<Item> LABEL_131 = block(MoreScpAlarmModBlocks.LABEL_131);
	public static final RegistryObject<Item> LABEL_143FR = block(MoreScpAlarmModBlocks.LABEL_143FR);
	public static final RegistryObject<Item> LABEL_143 = block(MoreScpAlarmModBlocks.LABEL_143);
	public static final RegistryObject<Item> DOCSTRANGE = REGISTRY.register("docstrange", () -> new DocstrangeItem());
	public static final RegistryObject<Item> DOC_008 = REGISTRY.register("doc_008", () -> new Doc008Item());
	public static final RegistryObject<Item> DOC_012 = REGISTRY.register("doc_012", () -> new Doc012Item());
	public static final RegistryObject<Item> DOC_035 = REGISTRY.register("doc_035", () -> new Doc035Item());
	public static final RegistryObject<Item> DOC_035AD = REGISTRY.register("doc_035ad", () -> new Doc035adItem());
	public static final RegistryObject<Item> DOC_038 = REGISTRY.register("doc_038", () -> new Doc038Item());
	public static final RegistryObject<Item> DOC_049 = REGISTRY.register("doc_049", () -> new Doc049Item());
	public static final RegistryObject<Item> DOC_079 = REGISTRY.register("doc_079", () -> new Doc079Item());
	public static final RegistryObject<Item> DOC_93ARM = REGISTRY.register("doc_93arm", () -> new Doc93armItem());
	public static final RegistryObject<Item> DOC_096 = REGISTRY.register("doc_096", () -> new Doc096Item());
	public static final RegistryObject<Item> DOC_1048 = REGISTRY.register("doc_1048", () -> new Doc1048Item());
	public static final RegistryObject<Item> DOC_1048A = REGISTRY.register("doc_1048a", () -> new Doc1048aItem());
	public static final RegistryObject<Item> DOC_106 = REGISTRY.register("doc_106", () -> new Doc106Item());
	public static final RegistryObject<Item> DOC_1062 = REGISTRY.register("doc_1062", () -> new Doc1062Item());
	public static final RegistryObject<Item> DOC_109 = REGISTRY.register("doc_109", () -> new Doc109Item());
	public static final RegistryObject<Item> DOC_1123 = REGISTRY.register("doc_1123", () -> new Doc1123Item());
	public static final RegistryObject<Item> DOC_1162 = REGISTRY.register("doc_1162", () -> new Doc1162Item());
	public static final RegistryObject<Item> DOC_1499 = REGISTRY.register("doc_1499", () -> new Doc1499Item());
	public static final RegistryObject<Item> DOC_173 = REGISTRY.register("doc_173", () -> new Doc173Item());
	public static final RegistryObject<Item> DOC_372 = REGISTRY.register("doc_372", () -> new Doc372Item());
	public static final RegistryObject<Item> DOC_427 = REGISTRY.register("doc_427", () -> new Doc427Item());
	public static final RegistryObject<Item> DOC_500 = REGISTRY.register("doc_500", () -> new Doc500Item());
	public static final RegistryObject<Item> DOC_513 = REGISTRY.register("doc_513", () -> new Doc513Item());
	public static final RegistryObject<Item> DOC_682 = REGISTRY.register("doc_682", () -> new Doc682Item());
	public static final RegistryObject<Item> DOC_714 = REGISTRY.register("doc_714", () -> new Doc714Item());
	public static final RegistryObject<Item> DOC_860 = REGISTRY.register("doc_860", () -> new Doc860Item());
	public static final RegistryObject<Item> DOC_8601 = REGISTRY.register("doc_8601", () -> new Doc8601Item());
	public static final RegistryObject<Item> DOC_895 = REGISTRY.register("doc_895", () -> new Doc895Item());
	public static final RegistryObject<Item> DOC_914 = REGISTRY.register("doc_914", () -> new Doc914Item());
	public static final RegistryObject<Item> DOC_939 = REGISTRY.register("doc_939", () -> new Doc939Item());
	public static final RegistryObject<Item> DOC_966 = REGISTRY.register("doc_966", () -> new Doc966Item());
	public static final RegistryObject<Item> DOC_970 = REGISTRY.register("doc_970", () -> new Doc970Item());
	public static final RegistryObject<Item> DOCAC = REGISTRY.register("docac", () -> new DocacItem());
	public static final RegistryObject<Item> DOCDAN = REGISTRY.register("docdan", () -> new DocdanItem());
	public static final RegistryObject<Item> DOCGONZALES = REGISTRY.register("docgonzales", () -> new DocgonzalesItem());
	public static final RegistryObject<Item> DOCL_1 = REGISTRY.register("docl_1", () -> new Docl1Item());
	public static final RegistryObject<Item> DOCL_2 = REGISTRY.register("docl_2", () -> new Docl2Item());
	public static final RegistryObject<Item> DOCL_3 = REGISTRY.register("docl_3", () -> new Docl3Item());
	public static final RegistryObject<Item> DOCL_4 = REGISTRY.register("docl_4", () -> new Docl4Item());
	public static final RegistryObject<Item> DOCL_5 = REGISTRY.register("docl_5", () -> new Docl5Item());
	public static final RegistryObject<Item> DOCL_6 = REGISTRY.register("docl_6", () -> new Docl6Item());
	public static final RegistryObject<Item> DOCMAP = REGISTRY.register("docmap", () -> new DocmapItem());
	public static final RegistryObject<Item> DOCMSP = REGISTRY.register("docmsp", () -> new DocmspItem());
	public static final RegistryObject<Item> DOCMTF = REGISTRY.register("docmtf", () -> new DocmtfItem());
	public static final RegistryObject<Item> DOCNDP = REGISTRY.register("docndp", () -> new DocndpItem());
	public static final RegistryObject<Item> DOCBJC = REGISTRY.register("docbjc", () -> new DocbjcItem());
	public static final RegistryObject<Item> DOCORI = REGISTRY.register("docori", () -> new DocoriItem());
	public static final RegistryObject<Item> DOCRAND_1 = REGISTRY.register("docrand_1", () -> new Docrand1Item());
	public static final RegistryObject<Item> GUIRAND_2 = REGISTRY.register("guirand_2", () -> new Guirand2Item());
	public static final RegistryObject<Item> GUIRAND_3 = REGISTRY.register("guirand_3", () -> new Guirand3Item());
	public static final RegistryObject<Item> DOCRP = REGISTRY.register("docrp", () -> new DocrpItem());
	public static final RegistryObject<Item> DOCSC = REGISTRY.register("docsc", () -> new DocscItem());
	public static final RegistryObject<Item> DOCARCE = REGISTRY.register("docarce", () -> new DocarceItem());
	public static final RegistryObject<Item> DOCF_5 = REGISTRY.register("docf_5", () -> new Docf5Item());
	public static final RegistryObject<Item> DOCF_4 = REGISTRY.register("docf_4", () -> new Docf4Item());
	public static final RegistryObject<Item> DOCF_6 = REGISTRY.register("docf_6", () -> new Docf6Item());
	public static final RegistryObject<Item> DOCIR_106 = REGISTRY.register("docir_106", () -> new Docir106Item());
	public static final RegistryObject<Item> CASSIESIGN = block(MoreScpAlarmModBlocks.CASSIESIGN);
	public static final RegistryObject<Item> ALARMSIREN = block(MoreScpAlarmModBlocks.ALARMSIREN);
	public static final RegistryObject<Item> NEWDOOR_PART = block(MoreScpAlarmModBlocks.NEWDOOR_PART);

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties()));
	}
}
