
/*
 *	MCreator note: This file will be REGENERATED on each build.
 */
package net.theo.scpalarm.init;

import net.theo.scpalarm.world.inventory.GuistrangeMenu;
import net.theo.scpalarm.world.inventory.GuiscMenu;
import net.theo.scpalarm.world.inventory.GuirpMenu;
import net.theo.scpalarm.world.inventory.Guirand1Menu;
import net.theo.scpalarm.world.inventory.GuioriMenu;
import net.theo.scpalarm.world.inventory.GuindpMenu;
import net.theo.scpalarm.world.inventory.GuimtfMenu;
import net.theo.scpalarm.world.inventory.GuimspMenu;
import net.theo.scpalarm.world.inventory.GuimapMenu;
import net.theo.scpalarm.world.inventory.Guil6Menu;
import net.theo.scpalarm.world.inventory.Guil5Menu;
import net.theo.scpalarm.world.inventory.Guil4Menu;
import net.theo.scpalarm.world.inventory.Guil3Menu;
import net.theo.scpalarm.world.inventory.Guil2Menu;
import net.theo.scpalarm.world.inventory.Guil1Menu;
import net.theo.scpalarm.world.inventory.Guiir106Menu;
import net.theo.scpalarm.world.inventory.GuigonzalesMenu;
import net.theo.scpalarm.world.inventory.Guif6Menu;
import net.theo.scpalarm.world.inventory.Guif5Menu;
import net.theo.scpalarm.world.inventory.Guif4Menu;
import net.theo.scpalarm.world.inventory.GuidanMenu;
import net.theo.scpalarm.world.inventory.GuibjoMenu;
import net.theo.scpalarm.world.inventory.GuiarceMenu;
import net.theo.scpalarm.world.inventory.GuiacMenu;
import net.theo.scpalarm.world.inventory.Gui970Menu;
import net.theo.scpalarm.world.inventory.Gui966Menu;
import net.theo.scpalarm.world.inventory.Gui93armMenu;
import net.theo.scpalarm.world.inventory.Gui939Menu;
import net.theo.scpalarm.world.inventory.Gui914Menu;
import net.theo.scpalarm.world.inventory.Gui895Menu;
import net.theo.scpalarm.world.inventory.Gui860Menu;
import net.theo.scpalarm.world.inventory.Gui8601Menu;
import net.theo.scpalarm.world.inventory.Gui714Menu;
import net.theo.scpalarm.world.inventory.Gui682Menu;
import net.theo.scpalarm.world.inventory.Gui513Menu;
import net.theo.scpalarm.world.inventory.Gui500Menu;
import net.theo.scpalarm.world.inventory.Gui427Menu;
import net.theo.scpalarm.world.inventory.Gui372Menu;
import net.theo.scpalarm.world.inventory.Gui173Menu;
import net.theo.scpalarm.world.inventory.Gui1499Menu;
import net.theo.scpalarm.world.inventory.Gui1162Menu;
import net.theo.scpalarm.world.inventory.Gui1123Menu;
import net.theo.scpalarm.world.inventory.Gui109Menu;
import net.theo.scpalarm.world.inventory.Gui106Menu;
import net.theo.scpalarm.world.inventory.Gui1062Menu;
import net.theo.scpalarm.world.inventory.Gui1048aMenu;
import net.theo.scpalarm.world.inventory.Gui1048Menu;
import net.theo.scpalarm.world.inventory.Gui096Menu;
import net.theo.scpalarm.world.inventory.Gui079Menu;
import net.theo.scpalarm.world.inventory.Gui049Menu;
import net.theo.scpalarm.world.inventory.Gui038Menu;
import net.theo.scpalarm.world.inventory.Gui035adMenu;
import net.theo.scpalarm.world.inventory.Gui035Menu;
import net.theo.scpalarm.world.inventory.Gui012Menu;
import net.theo.scpalarm.world.inventory.Gui008Menu;
import net.theo.scpalarm.world.inventory.Docrand3Menu;
import net.theo.scpalarm.world.inventory.Docrand2Menu;
import net.theo.scpalarm.MoreScpAlarmMod;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.extensions.IForgeMenuType;

import net.minecraft.world.inventory.MenuType;

public class MoreScpAlarmModMenus {
	public static final DeferredRegister<MenuType<?>> REGISTRY = DeferredRegister.create(ForgeRegistries.MENU_TYPES, MoreScpAlarmMod.MODID);
	public static final RegistryObject<MenuType<Gui008Menu>> GUI_008 = REGISTRY.register("gui_008", () -> IForgeMenuType.create(Gui008Menu::new));
	public static final RegistryObject<MenuType<GuistrangeMenu>> GUISTRANGE = REGISTRY.register("guistrange", () -> IForgeMenuType.create(GuistrangeMenu::new));
	public static final RegistryObject<MenuType<Gui012Menu>> GUI_012 = REGISTRY.register("gui_012", () -> IForgeMenuType.create(Gui012Menu::new));
	public static final RegistryObject<MenuType<Gui035Menu>> GUI_035 = REGISTRY.register("gui_035", () -> IForgeMenuType.create(Gui035Menu::new));
	public static final RegistryObject<MenuType<Gui035adMenu>> GUI_035AD = REGISTRY.register("gui_035ad", () -> IForgeMenuType.create(Gui035adMenu::new));
	public static final RegistryObject<MenuType<Gui038Menu>> GUI_038 = REGISTRY.register("gui_038", () -> IForgeMenuType.create(Gui038Menu::new));
	public static final RegistryObject<MenuType<Gui049Menu>> GUI_049 = REGISTRY.register("gui_049", () -> IForgeMenuType.create(Gui049Menu::new));
	public static final RegistryObject<MenuType<Gui079Menu>> GUI_079 = REGISTRY.register("gui_079", () -> IForgeMenuType.create(Gui079Menu::new));
	public static final RegistryObject<MenuType<Gui93armMenu>> GUI_93ARM = REGISTRY.register("gui_93arm", () -> IForgeMenuType.create(Gui93armMenu::new));
	public static final RegistryObject<MenuType<Gui096Menu>> GUI_096 = REGISTRY.register("gui_096", () -> IForgeMenuType.create(Gui096Menu::new));
	public static final RegistryObject<MenuType<Gui1048Menu>> GUI_1048 = REGISTRY.register("gui_1048", () -> IForgeMenuType.create(Gui1048Menu::new));
	public static final RegistryObject<MenuType<Gui1048aMenu>> GUI_1048A = REGISTRY.register("gui_1048a", () -> IForgeMenuType.create(Gui1048aMenu::new));
	public static final RegistryObject<MenuType<Gui106Menu>> GUI_106 = REGISTRY.register("gui_106", () -> IForgeMenuType.create(Gui106Menu::new));
	public static final RegistryObject<MenuType<Gui1062Menu>> GUI_1062 = REGISTRY.register("gui_1062", () -> IForgeMenuType.create(Gui1062Menu::new));
	public static final RegistryObject<MenuType<Gui109Menu>> GUI_109 = REGISTRY.register("gui_109", () -> IForgeMenuType.create(Gui109Menu::new));
	public static final RegistryObject<MenuType<Gui1123Menu>> GUI_1123 = REGISTRY.register("gui_1123", () -> IForgeMenuType.create(Gui1123Menu::new));
	public static final RegistryObject<MenuType<Gui1162Menu>> GUI_1162 = REGISTRY.register("gui_1162", () -> IForgeMenuType.create(Gui1162Menu::new));
	public static final RegistryObject<MenuType<Gui1499Menu>> GUI_1499 = REGISTRY.register("gui_1499", () -> IForgeMenuType.create(Gui1499Menu::new));
	public static final RegistryObject<MenuType<Gui173Menu>> GUI_173 = REGISTRY.register("gui_173", () -> IForgeMenuType.create(Gui173Menu::new));
	public static final RegistryObject<MenuType<Gui372Menu>> GUI_372 = REGISTRY.register("gui_372", () -> IForgeMenuType.create(Gui372Menu::new));
	public static final RegistryObject<MenuType<Gui427Menu>> GUI_427 = REGISTRY.register("gui_427", () -> IForgeMenuType.create(Gui427Menu::new));
	public static final RegistryObject<MenuType<Gui500Menu>> GUI_500 = REGISTRY.register("gui_500", () -> IForgeMenuType.create(Gui500Menu::new));
	public static final RegistryObject<MenuType<Gui513Menu>> GUI_513 = REGISTRY.register("gui_513", () -> IForgeMenuType.create(Gui513Menu::new));
	public static final RegistryObject<MenuType<Gui682Menu>> GUI_682 = REGISTRY.register("gui_682", () -> IForgeMenuType.create(Gui682Menu::new));
	public static final RegistryObject<MenuType<Gui714Menu>> GUI_714 = REGISTRY.register("gui_714", () -> IForgeMenuType.create(Gui714Menu::new));
	public static final RegistryObject<MenuType<Gui860Menu>> GUI_860 = REGISTRY.register("gui_860", () -> IForgeMenuType.create(Gui860Menu::new));
	public static final RegistryObject<MenuType<Gui8601Menu>> GUI_8601 = REGISTRY.register("gui_8601", () -> IForgeMenuType.create(Gui8601Menu::new));
	public static final RegistryObject<MenuType<Gui895Menu>> GUI_895 = REGISTRY.register("gui_895", () -> IForgeMenuType.create(Gui895Menu::new));
	public static final RegistryObject<MenuType<Gui914Menu>> GUI_914 = REGISTRY.register("gui_914", () -> IForgeMenuType.create(Gui914Menu::new));
	public static final RegistryObject<MenuType<Gui939Menu>> GUI_939 = REGISTRY.register("gui_939", () -> IForgeMenuType.create(Gui939Menu::new));
	public static final RegistryObject<MenuType<Gui966Menu>> GUI_966 = REGISTRY.register("gui_966", () -> IForgeMenuType.create(Gui966Menu::new));
	public static final RegistryObject<MenuType<Gui970Menu>> GUI_970 = REGISTRY.register("gui_970", () -> IForgeMenuType.create(Gui970Menu::new));
	public static final RegistryObject<MenuType<GuiacMenu>> GUIAC = REGISTRY.register("guiac", () -> IForgeMenuType.create(GuiacMenu::new));
	public static final RegistryObject<MenuType<GuidanMenu>> GUIDAN = REGISTRY.register("guidan", () -> IForgeMenuType.create(GuidanMenu::new));
	public static final RegistryObject<MenuType<GuigonzalesMenu>> GUIGONZALES = REGISTRY.register("guigonzales", () -> IForgeMenuType.create(GuigonzalesMenu::new));
	public static final RegistryObject<MenuType<Guiir106Menu>> GUIIR_106 = REGISTRY.register("guiir_106", () -> IForgeMenuType.create(Guiir106Menu::new));
	public static final RegistryObject<MenuType<Guil1Menu>> GUIL_1 = REGISTRY.register("guil_1", () -> IForgeMenuType.create(Guil1Menu::new));
	public static final RegistryObject<MenuType<GuimapMenu>> GUIMAP = REGISTRY.register("guimap", () -> IForgeMenuType.create(GuimapMenu::new));
	public static final RegistryObject<MenuType<GuimspMenu>> GUIMSP = REGISTRY.register("guimsp", () -> IForgeMenuType.create(GuimspMenu::new));
	public static final RegistryObject<MenuType<GuimtfMenu>> GUIMTF = REGISTRY.register("guimtf", () -> IForgeMenuType.create(GuimtfMenu::new));
	public static final RegistryObject<MenuType<GuindpMenu>> GUINDP = REGISTRY.register("guindp", () -> IForgeMenuType.create(GuindpMenu::new));
	public static final RegistryObject<MenuType<GuibjoMenu>> GUIBJC = REGISTRY.register("guibjc", () -> IForgeMenuType.create(GuibjoMenu::new));
	public static final RegistryObject<MenuType<GuioriMenu>> GUIORI = REGISTRY.register("guiori", () -> IForgeMenuType.create(GuioriMenu::new));
	public static final RegistryObject<MenuType<Guirand1Menu>> GUIRAND_1 = REGISTRY.register("guirand_1", () -> IForgeMenuType.create(Guirand1Menu::new));
	public static final RegistryObject<MenuType<GuirpMenu>> GUIRP = REGISTRY.register("guirp", () -> IForgeMenuType.create(GuirpMenu::new));
	public static final RegistryObject<MenuType<GuiscMenu>> GUISC = REGISTRY.register("guisc", () -> IForgeMenuType.create(GuiscMenu::new));
	public static final RegistryObject<MenuType<GuiarceMenu>> GUIARCE = REGISTRY.register("guiarce", () -> IForgeMenuType.create(GuiarceMenu::new));
	public static final RegistryObject<MenuType<Guif4Menu>> GUIF_4 = REGISTRY.register("guif_4", () -> IForgeMenuType.create(Guif4Menu::new));
	public static final RegistryObject<MenuType<Guif5Menu>> GUIF_5 = REGISTRY.register("guif_5", () -> IForgeMenuType.create(Guif5Menu::new));
	public static final RegistryObject<MenuType<Guif6Menu>> GUIF_6 = REGISTRY.register("guif_6", () -> IForgeMenuType.create(Guif6Menu::new));
	public static final RegistryObject<MenuType<Guil2Menu>> GUIL_2 = REGISTRY.register("guil_2", () -> IForgeMenuType.create(Guil2Menu::new));
	public static final RegistryObject<MenuType<Guil3Menu>> GUIL_3 = REGISTRY.register("guil_3", () -> IForgeMenuType.create(Guil3Menu::new));
	public static final RegistryObject<MenuType<Guil4Menu>> GUIL_4 = REGISTRY.register("guil_4", () -> IForgeMenuType.create(Guil4Menu::new));
	public static final RegistryObject<MenuType<Guil5Menu>> GUIL_5 = REGISTRY.register("guil_5", () -> IForgeMenuType.create(Guil5Menu::new));
	public static final RegistryObject<MenuType<Guil6Menu>> GUIL_6 = REGISTRY.register("guil_6", () -> IForgeMenuType.create(Guil6Menu::new));
	public static final RegistryObject<MenuType<Docrand2Menu>> DOCRAND_2 = REGISTRY.register("docrand_2", () -> IForgeMenuType.create(Docrand2Menu::new));
	public static final RegistryObject<MenuType<Docrand3Menu>> DOCRAND_3 = REGISTRY.register("docrand_3", () -> IForgeMenuType.create(Docrand3Menu::new));
}
